# Generated by Django 4.2.23 on 2025-08-06 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="বিভাগের নাম")),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "বিভাগ",
                "verbose_name_plural": "বিভাগসমূহ",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="শিরোনাম")),
                ("author", models.CharField(max_length=100, verbose_name="লেখক")),
                ("description", models.TextField(verbose_name="বিবরণ")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="মূল্য"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(upload_to="pdfs/", verbose_name="PDF ফাইল"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="thumbnails/",
                        verbose_name="থাম্বনেইল",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.category",
                        verbose_name="বিভাগ",
                    ),
                ),
            ],
            options={
                "verbose_name": "পণ্য",
                "verbose_name_plural": "পণ্যসমূহ",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="ক্রেতার নাম"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="ইমেইল")),
                ("phone", models.CharField(max_length=15, verbose_name="ফোন নম্বর")),
                (
                    "reference_no",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="রেফারেন্স নম্বর"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="পেমেন্ট সম্পন্ন"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="অনুমোদিত"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                        verbose_name="পণ্য",
                    ),
                ),
            ],
            options={
                "verbose_name": "অর্ডার",
                "verbose_name_plural": "অর্ডারসমূহ",
            },
        ),
    ]
