# Generated by Django 4.2.23 on 2025-08-13 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_order_options_remove_order_is_approved_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Ebook", "verbose_name_plural": "Ebooks"},
        ),
        migrations.AddField(
            model_name="product",
            name="sample_pdf_file",
            field=models.FileField(
                default=1, upload_to="sample_pdfs/", verbose_name=" Sample PDF File"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Category Name"),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer_name",
            field=models.CharField(max_length=100, verbose_name="Customer Name"),
        ),
        migrations.AlterField(
            model_name="order",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="order",
            name="phone",
            field=models.CharField(max_length=15, verbose_name="Phone No."),
        ),
        migrations.AlterField(
            model_name="product",
            name="author",
            field=models.CharField(max_length=100, verbose_name="Writer"),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="store.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="product",
            name="pdf_file",
            field=models.FileField(upload_to="pdfs/", verbose_name="PDF File"),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="price"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="thumbnails/",
                verbose_name="Thumbnail(200pxX200px)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
    ]
