# Generated by Django 4.2.23 on 2025-08-19 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_review"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="review",
            unique_together={("product", "email")},
        ),
        migrations.RemoveField(
            model_name="review",
            name="user",
        ),
    ]
