# Generated by Django 4.2.23 on 2025-08-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_review_unique_together_remove_review_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="downloads",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="thumbnails/",
                verbose_name="Thumbnail(250pxX200px)",
            ),
        ),
    ]
