# Generated by Django 4.2.23 on 2025-08-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_order_downloads_alter_product_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(
                decimal_places=2,
                default=500,
                max_digits=10,
                verbose_name="original_price",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="author",
            field=models.CharField(max_length=100, verbose_name="Author"),
        ),
    ]
