# Generated by Django 4.2.23 on 2025-08-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_product_original_price_alter_product_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pdf_file",
        ),
        migrations.AddField(
            model_name="product",
            name="drive_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
