# Generated by Django 4.2.23 on 2025-08-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_remove_product_pdf_file_product_drive_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="title",
        ),
    ]
